# Generated by Django 5.2.4 on 2025-07-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(blank=True, default='Default', max_length=100, null=True)),
                ('merchant', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='manual', max_length=10)),
            ],
        ),
    ]
